export const notificationsData = [
  {
    avatar: "/images/avatar-mark-webber.webp",
    name: "Mark Webber",
    message: "reacted to your recent post",
    link: "My first tournament today!",
    time: "1m ago",
    isRead: false,
  },
  {
    avatar: "/images/avatar-angela-gray.webp",
    name: "Angela Gray",
    message: "followed you",
    time: "5m ago",
    isRead: false,
  },
  {
    avatar: "/images/avatar-jacob-thompson.webp",
    name: "Jacob Thompson",
    message: "has joined your group",
    group: "Chess Club",
    time: "1 day ago",
    isRead: false,
  },
  {
    avatar: "/images/avatar-rizky-hasanuddin.webp",
    name: "Rizky Hasanuddin",
    message: "sent you a private message",
    privateMessage:
      "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    time: "5 days ago",
    isRead: true,
  },
  {
    avatar: "/images/avatar-kimberly-smith.webp",
    name: "Kimberly Smith",
    message: "commented on your picture",
    time: "1 week ago",
    isRead: true,
    image: "/images/image-chess.webp",
  },
  {
    avatar: "/images/avatar-nathan-peterson.webp",
    name: "Nathan Peterson",
    message: "reacted to your recent post",
    link: "5 end-game strategies to increase your win rate",
    time: "2 weeks ago",
    isRead: true,
  },
  {
    avatar: "/images/avatar-anna-kim.webp",
    name: "Anna Kim",
    message: "left the group",
    group: "Chess Club",
    time: "2 weeks ago",
    isRead: true,
  },
];
